-- 푸시 토큰 테이블 생성
CREATE TABLE IF NOT EXISTS PUSH_TOKEN (
    TOKEN_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '푸시 토큰 ID',
    EXPO_PUSH_TOKEN VARCHAR(255) NOT NULL UNIQUE COMMENT 'Expo 푸시 토큰',
    FARM_NUM INT NOT NULL COMMENT '농장 번호',
    DEVICE_ID VARCHAR(255) COMMENT '디바이스 ID',
    PLATFORM VARCHAR(20) COMMENT '플랫폼 (ios, android, web)',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    INDEX idx_farm_num (FARM_NUM),
    INDEX idx_device_id (DEVICE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='푸시 알림 토큰';

-- 외래키 설정 (CHICKEN_FARM 테이블과 연결)
-- ALTER TABLE PUSH_TOKEN
-- ADD CONSTRAINT fk_push_token_farm
-- FOREIGN KEY (FARM_NUM) REFERENCES CHICKEN_FARM(FARM_NUM)
-- ON DELETE CASCADE;